"""empty message

Revision ID: cc327289013c
Revises: 
Create Date: 2021-10-04 22:48:01.310421

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc327289013c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('language',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=256), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('text',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('txt', sa.String(length=128), nullable=False),
    sa.Column('readability', sa.Float(precision=32), nullable=False),
    sa.Column('lang_id', sa.Integer(), nullable=True),
    sa.Column('domain_id', sa.Integer(), nullable=True),
    sa.Column('length', sa.Integer(), nullable=True),
    sa.Column('rot', sa.Float(), nullable=False),
    sa.Column('conjunction', sa.Integer(), nullable=True),
    sa.Column('word_div', sa.Float(), nullable=True),
    sa.Column('longest', sa.Integer(), nullable=True),
    sa.Column('rare_word', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['domain_id'], ['domain.id'], ),
    sa.ForeignKeyConstraint(['lang_id'], ['language.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text')
    op.drop_table('language')
    op.drop_table('domain')
    # ### end Alembic commands ###
